receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

exporters:
  otlp:
    endpoint: "tempo:4317"
    tls:
      insecure: true
  debug: {}  # For debugging telemetry data in the console

  # prometheus:
  #   endpoint: "0.0.0.0:8888"

  zipkin:  # Use Zipkin exporter to send traces to Jaeger
    # endpoint: "http://jaeger:9411/api/v2/spans"
    endpoint: "http://jaeger:9411/api/v2/spans"


  file/logs:
    path: /tmp/otel_collector_logs.json
    format: json  # Export logs in JSON format for readability
  file/traces:
    path: /tmp/otel_collector_traces.json
    format: json  # Export traces in JSON format for readability

service:
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [debug, file/logs]  # File exporter should now work

    # metrics:
    #   receivers: [otlp]
    #   exporters: [prometheus]

    traces:
      receivers: [otlp]
      exporters: [file/traces, otlp]  # Zipkin exporter will send to Jaeger
  telemetry:
      logs:
        level: debug

# Docker Compose is now used to run the collector
# See docker-compose.yml in the project root
